# Write your code here :-)
from microbit import *
i2c.init()
print(i2c.scan())
I2C_COMMAND = 0x00

SETCONTRAST         = 0x81
DISPLAYALLONRESUME  = 0xA4
DISPLAYALLON        = 0xA5
NORMALDISPLAY       = 0xA6
INVERTDISPLAY       = 0xA7
DISPLAYOFF          = 0xAE
DISPLAYON           = 0xAF
SETDISPLAYOFFSET    = 0xD3
SETCOMPINS          = 0xDA
SETVCOMDESELECT     = 0xDB
SETDISPLAYCLOCKDIV  = 0xD5
SETPRECHARGE        = 0xD9
SETMULTIPLEX        = 0xA8
SETLOWCOLUMN        = 0x00
SETHIGHCOLUMN       = 0x10
SETSTARTLINE        = 0x40
MEMORYMODE          = 0x20
COMSCANINC          = 0xC0
COMSCANDEC          = 0xC8
SEGREMAP            = 0xA0
CHARGEPUMP          = 0x8D
EXTERNALVCC         = 0x01
SWITCHCAPVCC        = 0x02

buf = [I2C_COMMAND, DISPLAYOFF,
I2C_COMMAND, SETDISPLAYCLOCKDIV,
I2C_COMMAND, 0x80,
I2C_COMMAND, SETMULTIPLEX,
I2C_COMMAND, 0x2F,
I2C_COMMAND, SETDISPLAYOFFSET,
I2C_COMMAND, 0x00,
I2C_COMMAND, SETSTARTLINE | 0x0,
I2C_COMMAND, CHARGEPUMP,
I2C_COMMAND, 0x14,
I2C_COMMAND, NORMALDISPLAY,
I2C_COMMAND, DISPLAYALLONRESUME,
I2C_COMMAND, SEGREMAP | 0x1,
I2C_COMMAND, COMSCANDEC,
I2C_COMMAND, SETCOMPINS,
I2C_COMMAND, 0x12,
I2C_COMMAND, SETCONTRAST,
I2C_COMMAND, 0x8F,
I2C_COMMAND, SETPRECHARGE,
I2C_COMMAND, 0x22,
I2C_COMMAND, SETVCOMDESELECT,
I2C_COMMAND, 0x30,
I2C_COMMAND, DISPLAYON]

for i in range(len(buf)):
    i2c.write(0x3D, bytearray([buf[i]]))
